### ISSUE TITLE
Cannot install via pip

### ISSUE THREAD

**Issue by NicoHood** [seletz/ghrelease#14]
```
[arch@arch ~]$ pip install --user ghrelease
Collecting ghrelease
  Downloading ghrelease-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-wpmgzz_t/ghrelease/setup.py", line 8, in <module>
        from ghrelease import __version__
      File "/tmp/pip-build-wpmgzz_t/ghrelease/ghrelease/__init__.py", line 31, in <module>
        from docopt import docopt
    ModuleNotFoundError: No module named 'docopt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-wpmgzz_t/ghrelease/
```

**Comment by htgoebel** [comment]
Please try again, version 0.1.2 has been released in the meantime.

**Comment by htgoebel** [comment]
IC, 0.1.2 is not at PyPi. You can install it using
```
pip install https://github.com/seletz/ghrelease/releases/download/v0.1.2/ghrelease-0.1.2.tar.gz
```

**Comment by htgoebel** [comment]
@seletz Please upload release 0.1.2 to PyPI. Thanks.
